title: Research outputs - Arienne Calonge
description: Documentation of my recent work
theme: just-the-docs

url: https://arnclnge.github.io/researchoutputs

aux_links:
  Template Repository: https://github.com/arnclnge/researchoutputs
